Traceback (most recent call last):
  File "api.py", line 2, in <module>
    from rariblePipeline import create_clip_and_thumbnail
  File "/home/ubuntu/TwitchNFTBot/PythonNFTUtilities/rariblePipeline.py", line 10, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "api.py", line 2, in <module>
    from rariblePipeline import create_clip_and_thumbnail
  File "/home/ubuntu/TwitchNFTBot/PythonNFTUtilities/rariblePipeline.py", line 10, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "api.py", line 2, in <module>
    from rariblePipeline import create_clip_and_thumbnail
  File "/home/ubuntu/TwitchNFTBot/PythonNFTUtilities/rariblePipeline.py", line 10, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "api.py", line 2, in <module>
    from rariblePipeline import create_clip_and_thumbnail
  File "/home/ubuntu/TwitchNFTBot/PythonNFTUtilities/rariblePipeline.py", line 10, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "api.py", line 16, in <module>
    app.run(port=8080)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 666, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
167.248.23.98 - - [23/Aug/2021 22:59:39] "GET / HTTP/1.1" 200 -
167.248.23.98 - - [23/Aug/2021 22:59:39] "GET /favicon.ico HTTP/1.1" 404 -
Calling Rarible create
{'access_token': 'bb4kv8hbyd0u6kodfldmggnamrl5dv', 'expires_in': 15628, 'refresh_token': 'wdh2x2g0za771zxit29lvt9mpz0nklg2d0epdyirmg1iropf3y', 'scope': ['clips:edit'], 'token_type': 'bearer'}
Access Token: bb4kv8hbyd0u6kodfldmggnamrl5dv
Error: {'error': 'Not Found', 'status': 404, 'message': 'Clipping is not possible for an offline channel.'}
Clip Id: Error: Clipping is not possible for an offline channel.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
